openapi: 3.0.0

info:
  version: '1.0.0'
  title: 'API de Adição de Pratos'
  description: 'API para adicionar pratos em restaurantes'

paths:
  /pratos:
    post:
      summary: Adiciona um prato
      description: Adiciona um novo prato ao menu do restaurante.
      tags:
        - Pratos
      requestBody:
        description: Dados da requisição POST
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  description: Nome do prato
                descricao:
                  type: string
                  description: Descrição do prato
                preco:
                  type: number
                  format: double
                  description: Preço do prato
                imagem:
                  type: string
                  description: URL da imagem do prato
                tipo:
                  type: string
                  description: Tipo do prato
                disponivel:
                  type: integer
                  description: Quantidade disponível do prato
      responses:
        '200':
          description: Prato adicionado com sucesso
        '400':
          description: Campos obrigatórios ausentes
        '401':
          description: Token não fornecido ou inválido
        '403':
          description: Utilizador não tem permissão para adicionar pratos
        '500':
          description: Erro ao adicionar prato
      security:
        - BearerAuth: []
      servers:
        - url: 'http://localhost:3000/api'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
